version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=coders_blog
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=coders_blog
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 